### ISSUE TITLE
Make it more self-contained

### ISSUE THREAD

**Issue by JeroenDM** [JeroenDM/descartes_tutorials#4]
At the moment the tutorial depends on other custom packages in personal repositories. The kuka_kr120_robot is not a major problem I think because for building the [ikfast plugin](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/ikfast_tutorial.html) there exists a tutorial. For the descartes package, I can probably refer to a branch that has the changes for collision objects implemented.

**Comment by yijiangh** [comment]
In my personal understanding, a good tutorial can help new comers and novices to quickly start using the package, **without a lot of trouble**. Code and resources provided in the tutorial might serve has a **code template** (in my own experience yes!!!) to quickly get them started to develop their own project and application. As they get more experience, they might choose the abandon the tutorial's beginner level code architecture and go on to develop their own. 

Thus I think all the dependent customized packages (especially made for this tutorial, e.g. the kuka_kr6_robot package) should be covered. We can't expect a novice to find the correct kuka model, build their moveit_config and ik_fast package and correctly link them to your code and demo **with ease**.

In my view, it'll be good if you can simply put your [kuka_kr120_robot](https://github.com/JeroenDM/kuka_kr120_robot/tree/cd975b8a5df7b364d213ba3b0dbece3f3ff90585) package in your [main directory](https://github.com/JeroenDM/descartes_tutorials/tree/0a0a81cd2aae5296d26f34969d9a17b253b503a4). And list the catkin dependency for [kuka_experimental](https://github.com/ros-industrial/kuka_experimental/tree/d6e719fa261b515f1dd45acfb818a9a2c7b15309) in your compilation instruction, as your customized kuka_kr120_robot package are using stls from kuka_experimental package.

Personally I don't think it's necessary to have kuka_kr120_robot package as a meta-package, specified [here](https://github.com/JeroenDM/kuka_kr120_robot/blob/cd975b8a5df7b364d213ba3b0dbece3f3ff90585/kuka_kr120_robot/package.xml). (Maybe as a package container name, kuka_kr120_with_torch would be better?)

For descartes_tutorials repo, I think it's not necessary to have a meta package actually, just put them together so whenever we catkin_make, all the needed package will be built. 

So the proposed workspace might look like:

catkin_ws/
  - build/
  - devel/
  - src/
    - [descartes/](https://github.com/JeroenDM/descartes/tree/indigo-devel)
      - ...
    - [descartes_tutorials/](https://github.com/JeroenDM/descartes_tutorials)
      - descartes_tutorials/
        - src/
          - tutorial1.cpp
          - tutorial2.cpp
      - tutorial_utitilies/
      - [kuka_kr120_robot/](https://github.com/JeroenDM/kuka_kr120_robot) (suggest changing name to kuka_kr120_with_torch)
        - kuka_kr120_with_torch/
        - kuka_kr120_with_torch_ikfast/
        - kuka_kr120_with_torch_moveit_config/
      - [motoman_robot/](https://github.com/ros-industrial/motoman)
        - motoman_sia20d_support/
        - motoman_sia20d_moveit_config/
      - .gitignore
      - LICENSE
    - [kuka_experimental](https://github.com/ros-industrial/kuka_experimental)
    - [industrial_core](https://github.com/ros-industrial/industrial_core)
    - CMakeLists.txt

Thanks for your fantastic work, I learned a lot about descartes using this tutorial.

**Comment by yijiangh** [comment]
In regard of your question in our [google group discussion](https://groups.google.com/forum/#!topic/swri-ros-pkg-dev/pTa_H8SKqn8), I would say the best way to learn how to organize your package is to read other great package in your community. The specific organizing rules varies when you work with different communities and projects.

Luckily for ROS, this amazing community provides us tens of beautiful packages to read and learn.

**Comment by JeroenDM** [comment]
Thank you! I will look at some other packages, good point. I mainly looked at the descartes repo up until now. I'm passing the compliments to @Bart123456, who did most of the actual coding for this tutorial.

**Comment by JeroenDM** [comment]
I agree with the new name "kuka_kr120_with_torch. In the proposed workspace layout, the motoman package is not necessary I think. This should be installed when using rosdep as explained in [the tutorial](http://wiki.ros.org/descartes/Tutorials/Getting%20Started%20with%20Descartes). Although I just noticed this dependency fix [has yet to be merged](https://github.com/ros-industrial-consortium/descartes_tutorials/pull/5).

**Comment by JeroenDM** [comment]
I updated the readme. I think it should be a little bit more clear now how to install and use this package. I will look for som people who never used it to test the instructions.
