### ISSUE TITLE
branch name needs to conform to ros convention

### ISSUE THREAD

**Issue by yijiangh** [JeroenDM/descartes_tutorials#5]
Refer to issue #1.

Vincent's [branching model](http://nvie.com/posts/a-successful-git-branching-model/) is about a general strategy for organizing code, it can be implemented according to specific convention when applied to specific project.

Take a look at other mature ros package's branch arrangment, e.g. [navigation](https://github.com/ros-planning/navigation) and [industrial_moveit](https://github.com/ros-industrial/industrial_moveit). You might find something similar in their branch arrangment:

  - develop branch (in branching model)
     - indigo-devel
     - <other_ros_release>-devel
     - ...
  - master (release) branch
     - indigo
     - kinetic
     - ...
  - feature branch (as ros community is not obliged to use branching model, some time you might find feature branch without "feature" prefix, e.g. [here](https://github.com/ros-planning/navigation/tree/fecdad8037f40f85ecd1673ecc897684e0e41ebf))
    - feature/<your_feature>

It might be beneficial to take a look at some well-organized tutorial package, like [navigation_tutorials](https://github.com/ros-planning/navigation_tutorials). Check the branch arrangment, coding and documenting style and learn from them.

Just FYI, this [ros cpp style guide](http://wiki.ros.org/CppStyleGuide) is really helpful (just in case you haven't read it).

**Comment by JeroenDM** [comment]
Thanks for the links to example repos. I read the cpp style guide, but conforming to it is an another story. I just found [this auto-formatting tool](https://github.com/davetcoleman/roscpp_code_format) to help me.

**Comment by JeroenDM** [comment]
I changed the name of the develop branch to indigo-devel and removed the branch with the original code since this was redundant.

**Comment by JeroenDM** [comment]
(Although if things change in the original repository of the fork and we would do a pull request, there could be extra merge conflicts.)
